[package]
name = "sw4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sw4_macros = {path = "./macros"}

[workspace]
members = ["macros"]

[features]
panic_handler = []